project:
  type: website
  output-dir: docs

website:
  title: "Jackie Chen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - photos-videos.qmd

format:
  html:
    theme: quartz
    css: styles.css
    toc: true
    page-layout: full

editor: visual

